version: '3.8'
services:

  postgres:
    image: postgres:15.3            #TODO lastest version on June 2023
    restart: always
    environment:
      - POSTGRES_USER=user          #? can be changed
      - POSTGRES_PASSWORD=password  #? can be changed
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432' 

volumes:
  postgres: